### ISSUE TITLE
Gocore metrics should support Datadog-style metrics tagging

### ISSUE THREAD

**Issue by nsheridan** [intercom/gocore#11]
As part of the move from Graphite to Datadog the expected metric format will change.
Unfortunately the metrics package doesn't support metrics tagging.

Some background:
In graphite it's possible (and encouraged) to select metrics using wildcards, e.g.
`stats.counts.argus.*.tailed_records`.
In Datadog, selecting metrics using wildcards is not supported. The supported mechanism for selecting a series of metrics in Datadog is to generalise the metric name and use tags to select metrics. For example, the above would look like:
`stats.counts.argus.tailed_records{replicaset=0, replicaset=1, replicaset=2,replicaset=...}` and the top10 of these be queried using e.g. `top(sum:stats.counts.argus.tailed_records{*} by {replicaset}, 10)`.

https://github.com/armon/go-metrics has a datadog package (https://github.com/armon/go-metrics/tree/master/datadog) but it doesn't support per-metrics tagging - setting `replicaset` on the above example is not possible. It does allow for global tags, which will be applied to all metrics.

Possible options:
- Modify armon/go-metrics/datadog to accept tags per-metric.
- Use a different metrics package which understands datadog (http://docs.datadoghq.com/libraries/).

**Comment by nsheridan** [comment]
cc @josler

**Comment by josler** [comment]
Looking at this for this week. I guess that what would be most useful from an API perspective would be to do something like:

```go
metrics.withTag("key", "value").IncrementCountBy("metricName", 2)

// and with some reuse:
taggedMetrics := metrics.withTag("key", "value")
taggedMetrics.IncrementCountBy("metricName", 2)
taggedMetrics.SetGauge("anotherMetric", 4.2)
```

Then from there do the right thing.

**Comment by josler** [comment]
Done!
